---
  - name: show hostname
    hosts: iosswitch
    gather_facts: no
    connection: network_cli

    tasks:
        - name: show-outputs ### Task Show Output ####
          ios_command:
            #provider: "{{ crdentials }}"
            commands:
              - show run | i hostname
          register: output
        - name: print output
          debug:
            var: output.stdout_lines
        - name: Creates directory
          ansible.builtin.file:
            path: /ITNC_backup/test-2
            state: directory
